apiVersion: v1
kind: Service
metadata:
  name: trainer
spec:
  clusterIP: None # <-- makes it headless
  selector:
    app: trainer
  ports:
    - name: dist
      port: 29500
      targetPort: 29500
